cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./.cargo
    - target

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

deploy:
  stage: deploy
  script:
    - echo "world"
