cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./.cargo
    - target

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

build:
  stage: build
  before_script:
    - docker login -u dimashur -p $ACCESS_TOKEN $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/dimashur/productivity:latest --target production .
    - docker push $CI_REGISTRY/dimashur/productivity:latest

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts

  script:
    - ssh root@$DEPLOYMENT_SERVER_IP "cd /usr/src; rm -rf productivity; git clone git@gitlab.com:dimashur/productivity.git; cd productivity; docker-compose -f docker-compose.prod.yml down; docker-compose -f docker-compose.prod.yml up"
