cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./.cargo
    - target

stages:
  - test
  - build
  - review
  - deploy

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

build:
  stage: build
  before_script:
    - docker login -u dimashur -p $ACCESS_TOKEN $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/dimashur/productivity:${CI_COMMIT_REF_SLUG} --target production .
    - docker push $CI_REGISTRY/dimashur/productivity:${CI_COMMIT_REF_SLUG}

review:
  stage: review
  only:
    - branches
  except:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "\nCI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG" >> $PROD_ENV
    - printf "\nNGINX_HOST_PORT=0" >> $PROD_ENV
    - touch env
    - cat $PROD_ENV > env
    - rsync -r ./docker-compose.prod.yml db env nginx root@${DEPLOYMENT_SERVER_IP}:/usr/src/productivity/$CI_COMMIT_REF_SLUG
    - ssh root@$DEPLOYMENT_SERVER_IP "cd /usr/src/productivity/$CI_COMMIT_REF_SLUG; export $(cat env | xargs); docker login -u dimashur -p ${ACCESS_TOKEN} ${CI_REGISTRY}; docker-compose -f docker-compose.prod.yml stop; docker-compose -f docker-compose.prod.yml rm productivity_back --force; docker pull ${CI_REGISTRY}/dimashur/productivity:latest; docker-compose -f docker-compose.prod.yml up -d; docker container ls | grep $CI_COMMIT_REF_SLUG"
    - rm env

deploy:
  stage: deploy
  when: manual
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "\nCI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG" >> $PROD_ENV
    - printf "\nNGINX_HOST_PORT=80" >> $PROD_ENV
    - touch env
    - cat $PROD_ENV > env
    - rsync -r ./docker-compose.prod.yml db env nginx root@${DEPLOYMENT_SERVER_IP}:/usr/src/productivity/$CI_COMMIT_REF_SLUG
    - ssh root@$DEPLOYMENT_SERVER_IP "cd /usr/src/productivity/$CI_COMMIT_REF_SLUG; export $(cat env | xargs); docker login -u dimashur -p ${ACCESS_TOKEN} ${CI_REGISTRY}; docker-compose -f docker-compose.prod.yml stop; docker-compose -f docker-compose.prod.yml rm productivity_back --force; docker pull ${CI_REGISTRY}/dimashur/productivity:latest; docker-compose -f docker-compose.prod.yml up -d"
    - rm env
