stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - docker info
    - docker-compose -v
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

deploy:
  stage: deploy
  script:
    - echo "world"
