stages:
  - test
  - deploy

test:
  stage: test
  image:
    name: docker/compose:1.25.4
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2357
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker-compose -v
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit

deploy:
  stage: deploy
  script:
    - echo "world"
