[[runners]]
  url = "https://gitlab.com/"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.8"
    privileged = true
    disable_cache = false
    volumes = ["/certs/client", "/cache"]