version: '3.7'

services:
  productivity_back:
    build:
      context: ./
      target: development
    container_name: productivity_back
    environment:
      POSTGRES_URL: "postgres://dshur:1234@postgres:5432/productivity?sslmode=disable"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    container_name: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dshur
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: productivity
  redis:
    image: redis:5.0.8
    container_name: redis
    ports:
      - 6379:6379
