version: '3.7'

services:
  productivity_back:
    build:
      context: ./
      target: test
    environment:
      POSTGRES_URL: "postgres://dshur:1234@postgres:5432/productivity?sslmode=disable"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "dshur"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "productivity"
      PRODUCTIVITY_HOST: "127.0.0.1"
      PRODUCTIVITY_PORT: "5555"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - 5555:5555
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dshur
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: productivity
  redis:
    image: redis:5.0.8
    ports:
      - 6379:6379
