version: '3.7'

services:
  productivity_back:
    image: registry.gitlab.com/dimashur/productivity:latest
    environment:
      CARGO_HOME: ./.cargo
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/productivity?sslmode=disable
      PRODUCTIVITY_HOST: ${DEPLOYMENT_SERVER_IP}
      PRODUCTIVITY_PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productivity
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
    ports:
      - 80:80
  postgres:
    image: postgres:12.2
    container_name: postgres
    volumes:
      - postgres_productivity:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productivity
  redis:
    image: redis:5.0.8
    container_name: redis
    ports:
      - 6379:6379

volumes:
  postgres_productivity:
