version: '3.7'

services:
  nginx:
    image: nginx:1.18.0
    volumes:
    - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - productivity_back
  productivity_back:
    container_name: productivity_back
    image: registry.gitlab.com/dimashur/productivity:${CI_COMMIT_REF_SLUG}
    env_file:
      - env
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    container_name: postgres
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productivity
  redis:
    image: redis:5.0.8
    container_name: redis

volumes:
  postgres_productivity:
  postgres_productivity_test:
