version: '3.7'

services:
  productivity_back:
    image: registry.gitlab.com/dimashur/productivity:${CI_COMMIT_REF_SLUG}
    env_file:
      - env
    depends_on:
      - postgres
    networks:
      - productivity_network
  postgres:
    image: postgres:12.2
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productivity
    networks:
      - productivity_network
  redis:
    image: redis:5.0.8
    networks:
      - productivity_network

volumes:
  postgres_productivity:
  postgres_productivity_test:

networks:
  productivity_network:
    external:
      name: productivity
